# Generated by Django 4.2.4 on 2023-08-24 11:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PointSystem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('point_type', models.CharField(choices=[('paid', 'Paid'), ('unpaid', 'Unpaid')], max_length=6)),
                ('value', models.IntegerField()),
                ('threshold_upper', models.IntegerField(default=999)),
                ('threshold_lower', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='StarSystem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=15, null=True)),
                ('value', models.IntegerField()),
                ('threshold_upper', models.IntegerField(default=999)),
                ('threshold_lower', models.IntegerField()),
            ],
        ),
        migrations.RenameField(
            model_name='ratinghistory',
            old_name='stars',
            new_name='stars_change',
        ),
        migrations.RemoveField(
            model_name='employer',
            name='joined_date',
        ),
        migrations.AlterField(
            model_name='payment',
            name='employer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='main.employer'),
        ),
        migrations.AlterField(
            model_name='rating',
            name='employer',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='main.employer'),
        ),
        migrations.AlterField(
            model_name='ratinghistory',
            name='rating',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='history', to='main.rating'),
        ),
        migrations.AddField(
            model_name='rating',
            name='star_rating',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='main.starsystem'),
        ),
    ]
