# Generated by Django 4.2.4 on 2023-08-24 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_pointsystem_starsystem_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pointsystem',
            name='threshold_upper',
            field=models.IntegerField(default=9999),
        ),
        migrations.AlterField(
            model_name='starsystem',
            name='label',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='starsystem',
            name='threshold_upper',
            field=models.IntegerField(default=9999),
        ),
    ]
