# Generated by Django 4.2.4 on 2023-08-24 12:18

from django.db import migrations

def add_default_point_rating_systems(apps, schema_editor):
    PointSystem = apps.get_model("main", "PointSystem")
    PointSystem.objects.bulk_create([
        PointSystem(point_type="paid", value=3, threshold_upper=0, threshold_lower=-30),
        PointSystem(point_type="paid", value=2, threshold_upper=90, threshold_lower=1),
        PointSystem(point_type="paid", value=1, threshold_upper=99999, threshold_lower=91),
        PointSystem(point_type="unpaid", value=-3, threshold_upper=99999, threshold_lower=91),
    ])

def add_default_star_rating_systems(apps, schema_editor):
    StarSystem = apps.get_model("main", "StarSystem")
    StarSystem.objects.bulk_create([
        StarSystem(label="Platinum", value=5, threshold_upper=99999, threshold_lower=12),
        StarSystem(label="Gold", value=4, threshold_upper=11, threshold_lower=6),
        StarSystem(label="Silver", value=3, threshold_upper=5, threshold_lower=3),
        StarSystem(label="Crawler", value=0, threshold_upper=2, threshold_lower=0),
    ])


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_alter_pointsystem_threshold_upper_and_more'),
    ]

    operations = [

        migrations.RunPython(add_default_star_rating_systems),
    ]
