# Generated by Django 4.2.4 on 2023-08-24 12:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_auto_20230824_1218'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rating',
            name='star_rating',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.PROTECT, to='main.starsystem'),
        ),
    ]
